version: '3.3'
services:

  web:
    build: '.'
    container_name: 'helloweb'
    ports:
      - '1234:1234'
    healthcheck:
      test: curl --fail -s http://localhost:1234/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  prometheus:
    build: './prometheus'
    container_name: 'prometheus'
    ports:
      - '9090:9090'

  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - '3000:3000'

  node_exporter:
    image: 'quay.io/prometheus/node-exporter'
    container_name: 'node_exporter'
